import { StorageBlock } from "./helpers";

export const expectedStorageBlocks = [
    { id: "0", isFreeSpace: false },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: "1", isFreeSpace: false },
    { id: "1", isFreeSpace: false },
    { id: "1", isFreeSpace: false },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: "2", isFreeSpace: false },
    { id: "2", isFreeSpace: false },
    { id: "2", isFreeSpace: false },
    { id: "2", isFreeSpace: false },
    { id: "2", isFreeSpace: false },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
] as StorageBlock[];

export const expectedDefragmentedStorageBlocks = [
    { id: "0", isFreeSpace: false },
    { id: "2", isFreeSpace: false },
    { id: "2", isFreeSpace: false },
    { id: "1", isFreeSpace: false },
    { id: "1", isFreeSpace: false },
    { id: "1", isFreeSpace: false },
    { id: "2", isFreeSpace: false },
    { id: "2", isFreeSpace: false },
    { id: "2", isFreeSpace: false },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
] as StorageBlock[];

export const storageBlocksToDefragmentByFile = [
    { id: "0", isFreeSpace: false },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: "1", isFreeSpace: false },
    { id: "1", isFreeSpace: false },
    { id: "1", isFreeSpace: false },
    { id: "1", isFreeSpace: false },
    { id: null, isFreeSpace: true },
    { id: "2", isFreeSpace: false },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: "3", isFreeSpace: false },
    { id: "3", isFreeSpace: false },
    { id: "3", isFreeSpace: false },
    { id: "3", isFreeSpace: false },
    { id: "3", isFreeSpace: false },
    { id: null, isFreeSpace: true },
] as StorageBlock[];

export const expectedDefragmentedByFilesStorageBlocks = [
    { id: "0", isFreeSpace: false },
    { id: "2", isFreeSpace: false },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: "1", isFreeSpace: false },
    { id: "1", isFreeSpace: false },
    { id: "1", isFreeSpace: false },
    { id: "1", isFreeSpace: false },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: "3", isFreeSpace: false },
    { id: "3", isFreeSpace: false },
    { id: "3", isFreeSpace: false },
    { id: "3", isFreeSpace: false },
    { id: "3", isFreeSpace: false },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
    { id: null, isFreeSpace: true },
] as StorageBlock[];
